### ISSUE TITLE
Crash when attempting to use

### ISSUE THREAD

**Issue by leighman** [spatie/phpunit-watcher#110]
- Install version 1.10 with composer
- Add a phpunit-watcher.yml
```
watch:
  directories:
    - blah/tests
  fileMask: '*.php'
```
- phpunit-watcher presents options
- Press `p`
- Nothing happens
- Press `Enter`

Crash:
```
PHP Error:  Call to private method Clue\React\Stdio\Readline::deleteChar() from context 'Spatie\PhpUnitWatcher\Terminal' in /vagrant/vendor/spatie/phpunit-watcher/src/Terminal.php on line 37
PHP Stack trace:
PHP   1. {main}() /vagrant/vendor/spatie/phpunit-watcher/phpunit-watcher:0
PHP   2. Spatie\PhpUnitWatcher\ConsoleApplication->run() /vagrant/vendor/spatie/phpunit-watcher/phpunit-watcher:15
PHP   3. Spatie\PhpUnitWatcher\ConsoleApplication->doRun() /vagrant/vendor/symfony/console/Application.php:145
PHP   4. Spatie\PhpUnitWatcher\ConsoleApplication->doRunCommand() /vagrant/vendor/symfony/console/Application.php:269
PHP   5. Spatie\PhpUnitWatcher\WatcherCommand->run() /vagrant/vendor/symfony/console/Application.php:917
PHP   6. Spatie\PhpUnitWatcher\WatcherCommand->execute() /vagrant/vendor/symfony/console/Command/Command.php:255
PHP   7. Spatie\PhpUnitWatcher\Watcher->startWatching() /vagrant/vendor/spatie/phpunit-watcher/src/WatcherCommand.php:30
PHP   8. React\EventLoop\StreamSelectLoop->run() /vagrant/vendor/spatie/phpunit-watcher/src/Watcher.php:57
PHP   9. React\EventLoop\StreamSelectLoop->waitForStreamActivity() /vagrant/vendor/react/event-loop/src/StreamSelectLoop.php:212
PHP  10. React\Stream\ReadableResourceStream->handleData() /vagrant/vendor/react/event-loop/src/StreamSelectLoop.php:245
PHP  11. React\Stream\ReadableResourceStream->emit() /vagrant/vendor/react/stream/src/ReadableResourceStream.php:146
PHP  12. Clue\React\Term\ControlCodeParser->handleData() /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:123
PHP  13. Clue\React\Term\ControlCodeParser->emit() /vagrant/vendor/clue/term-react/src/ControlCodeParser.php:136
PHP  14. Clue\React\Stdio\Readline->Clue\React\Stdio\{closure:/vagrant/vendor/clue/stdio-react/src/Readline.php:71-99}() /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:123
PHP  15. Clue\React\Stdio\Readline->onKeyEnter() /vagrant/vendor/clue/stdio-react/src/Readline.php:96
PHP  16. Clue\React\Stdio\Readline->processLine() /vagrant/vendor/clue/stdio-react/src/Readline.php:713
PHP  17. Clue\React\Stdio\Readline->emit() /vagrant/vendor/clue/stdio-react/src/Readline.php:862
PHP  18. Clue\React\Stdio\Stdio->Clue\React\Stdio\{closure:/vagrant/vendor/clue/stdio-react/src/Stdio.php:47-51}() /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:123
PHP  19. Clue\React\Stdio\Stdio->emit() /vagrant/vendor/clue/stdio-react/src/Stdio.php:50
PHP  20. Spatie\PhpUnitWatcher\Terminal->Spatie\PhpUnitWatcher\{closure:/vagrant/vendor/spatie/phpunit-watcher/src/Terminal.php:36-39}() /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php:131
PHP Fatal error:  Uncaught Error: Call to private method Clue\React\Stdio\Readline::deleteChar() from context 'Spatie\PhpUnitWatcher\Terminal' in /vagrant/vendor/spatie/phpunit-watcher/src/Terminal.php:37
Stack trace:
#0 /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(131): Spatie\PhpUnitWatcher\Terminal->Spatie\PhpUnitWatcher\{closure}('p\n')
#1 /vagrant/vendor/clue/stdio-react/src/Stdio.php(50): Evenement\EventEmitter->emit('data', Array)
#2 /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\Stdio\Stdio->Clue\React\Stdio\{closure}('p\n')
#3 /vagrant/vendor/clue/stdio-react/src/Readline.php(862): Evenement\EventEmitter->emit('data', Array)
#4 /vagrant/vendor/clue/stdio-react/src/Readline.php(713): Clue\React\Stdio\Readline->processLine('\n')
#5 /vagrant/vendor/clue/stdio-react/src/Readline.php(96): Clue\React\Stdio\Readline->onKeyEnter('\n')
#6 /vagrant/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\Stdio\Readline->Clue\React\Stdio\ in /vagrant/vendor/spatie/phpunit-watcher/src/Terminal.php on line 37
```

**Comment by leighman** [comment]
Now wondering why composer chose 1.10...

**Comment by karneaud** [comment]
I am also experiencing this issue? Is there a solution?
