### ISSUE TITLE
Fatal error: Uncaught Error: Call to private method Clue\React\Stdio\Readline::deleteCha

### ISSUE THREAD

**Issue by didaquis** [spatie/phpunit-watcher#96]
I am getting this error while trying to run the tests.
Can anyone help me?

I have phpunit-watcher installed locally. 
```
Fatal error: Uncaught Error: Call to private method Clue\React\Stdio\Readline::deleteChar() from context 'Spatie\PhpUnitWatcher\Terminal' in /Users/didac/repos/php-kata-boilerplate/vendor/spatie/phpunit-watcher/src/Terminal.php:37
Stack trace:
#0 /Users/didac/repos/php-kata-boilerplate/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(131): Spatie\PhpUnitWatcher\Terminal->Spatie\PhpUnitWatcher\{closure}('a\n')
#1 /Users/didac/repos/php-kata-boilerplate/vendor/clue/stdio-react/src/Stdio.php(50): Evenement\EventEmitter->emit('data', Array)
#2 /Users/didac/repos/php-kata-boilerplate/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\Stdio\Stdio->Clue\React\Stdio\{closure}('a\n')
#3 /Users/didac/repos/php-kata-boilerplate/vendor/clue/stdio-react/src/Readline.php(862): Evenement\EventEmitter->emit('data', Array)
#4 /Users/didac/repos/php-kata-boilerplate/vendor/clue/stdio-react/src/Readline.php(713): Clue\React\Stdio\Readline->processLine('\n')
#5 /Users/didac/repos/php-kata-boilerplat in /Users/didac/repos/php-kata-boilerplate/vendor/spatie/phpunit-watcher/src/Terminal.php on line 37
```

**Comment by JayBizzle** [comment]
Have you updated to the latest `phpunit-watcher` version?

Probably related to this - https://github.com/spatie/phpunit-watcher/pull/94

**Comment by didaquis** [comment]
> Have you updated to the latest phpunit-watcher version?

Yes. Do you have another idea to fix my problem?
